# Architecture combination: encoder=basic + decoder=unetpp
# 架构组合：编码器=Basic + 解码器=UNet++

model:
  num_classes: 2
  img_size: 256
  encoder:
    name: basic
    in_channels: 3
    params: {}
  decoder:
    name: unetpp
    params: {}
  bottleneck:
    name: none
data:
  type: generic
  img_size: 256
  train_dir: ./data/YourDataset/train
  val_dir: ./data/YourDataset/val
  test_dir: ./data/YourDataset/test
training:
  epochs: 300
  batch_size: 24
  num_workers: 4
  loss:
    name: compound
    params:
      losses:
      - name: ce
        weight: 0.4
      - name: dice
        weight: 0.6
  optimizer:
    name: adamw
    lr: 0.001
    weight_decay: 0.0001
  scheduler:
    name: cosine
    min_lr: 1.0e-06
