# Source: https://github.com/JCruan519/VM-UNet
# Architecture combination: encoder=vmunet + decoder=vmunet
# 架构组合：编码器=VMUNet + 解码器=vmunet

model:
  num_classes: 2
  img_size: 256
  encoder:
    name: vmunet
    pretrained: false
    in_channels: 3
    params:
      embed_dim: 96
      depths:
      - 2
      - 2
      - 9
      - 2
  decoder:
    name: vmunet
    params:
      embed_dim: 96
      depths_decoder:
      - 2
      - 9
      - 2
      - 2
  bottleneck:
    name: none
data:
  type: generic
  img_size: 256
  train_dir: ./data/YourDataset/train
  val_dir: ./data/YourDataset/val
  test_dir: ./data/YourDataset/test
training:
  epochs: 300
  batch_size: 24
  num_workers: 4
  loss:
    name: compound
    params:
      losses:
      - name: ce
        weight: 0.4
      - name: dice
        weight: 0.6
  optimizer:
    name: adamw
    lr: 0.001
    weight_decay: 0.01
  scheduler:
    name: cosine
    min_lr: 1.0e-06
