model:
  num_classes: 2
  img_size: 256
  encoder:
    name: basic
    pretrained: false
    in_channels: 3
    params: {}
  decoder:
    name: bilinear
    params: {}
  skip_connection:
    name: concat
    params: {}
  bottleneck:
    name: dense_aspp
    params: {}
data:
  type: generic
  img_size: 256
  train_dir: ./data/YourDataset/train
  val_dir: ./data/YourDataset/val
training:
  random_state: 42
  epochs: 200
  batch_size: 8
  num_workers: 4
  loss:
    name: compound
    params:
      losses:
      - name: ce
        weight: 0.4
      - name: dice
        weight: 0.6
  optimizer:
    name: adamw
    lr: 0.0001
  scheduler:
    name: cosine
    min_lr: 1.0e-06
