# Source: https://github.com/eatbeanss/CSWin-UNet
# Network: cswin_unet (complete architecture)
# 完整网络：cswin_unet（完整架构）

model:
  num_classes: 4
  img_size: 224
  architecture: cswin_unet
  encoder:
    in_channels: 3
  arch_params:
    embed_dim: 64
    depths:
    - 2
    - 2
    - 2
    - 2
    num_heads:
    - 2
    - 4
    - 8
    - 16
    split_size:
    - 1
    - 2
    - 7
    - 7
    drop_path_rate: 0.1
data:
  type: acdc
  img_size: 224
  train_dir: ./data/ACDC/train_npz
  test_dir: ./data/ACDC/test_vol_h5
  train_list: ./data/ACDC/lists/train.txt
  test_list: ./data/ACDC/lists/test_vol.txt
training:
  epochs: 300
  batch_size: 24
  num_workers: 4
  loss:
    name: compound
    params:
      losses:
      - name: ce
        weight: 0.4
      - name: dice
        weight: 0.6
  optimizer:
    name: adamw
    lr: 0.0005
    weight_decay: 0.05
  scheduler:
    name: cosine
    min_lr: 1.0e-06
