# Source: https://github.com/MIC-DKFZ/nnUNet
# Network: nnunet_2d (complete architecture)
# 完整网络：nnunet_2d（完整架构）

model:
  architecture: nnunet_2d
  num_classes: 4
  img_size: 224
  encoder:
    in_channels: 3
  arch_params: {}
data:
  type: acdc
  img_size: 224
  train_dir: ./data/ACDC/train_npz
  test_dir: ./data/ACDC/test_vol_h5
  train_list: ./data/ACDC/lists/train.txt
  test_list: ./data/ACDC/lists/test_vol.txt
training:
  epochs: 200
  batch_size: 24
  num_workers: 4
  loss:
    name: compound
    params:
      losses:
      - name: ce
        weight: 0.4
      - name: dice
        weight: 0.6
  optimizer:
    name: adamw
    lr: 0.01
    weight_decay: 3.0e-05
    momentum: 0.99
  scheduler:
    name: poly
    min_lr: 1.0e-06
    power: 0.9
